### ISSUE TITLE
Hide or close Terminal after process (enhancement)

### ISSUE THREAD

**Issue by Neberheim** [dricard/dolog#3]
Is it possible for the entry to work in the background? I don’t love that Terminal pops into the foreground and remains open. I tried messing around with `&& exit` and some other commands but I’m not sure how to execute the process properly.

**Comment by dricard** [comment]
I don't think it's possible for the script to work in the background. DayOne offers a CLI tool but no other method of interaction. My doto script, which sends a todo to Things, works without the terminal because Things supports an URL scheme. Note that Things will open, so it's not exactly "working in the background."
As a developer Terminal (or rather iTerm) is always open, so it never bothered me, but I'll see if I can arrange something to at least close the Terminal after the command has worked. Would that be ok?

**Comment by dricard** [comment]
Ok so I added an Alfred Workflow which quits the Terminal application after the script runs. You should probably change a default preference in Terminal. Follow these steps:
- open Terminal preferences
- select 'Profiles'
- select the 'Shell' tab
- select 'Never' in Ask before closing
- select 'Close the window' under 'When the shell exits'
- close the preferences' window

**Comment by dricard** [comment]
So, install the new workflow and test it out after changing the Terminal preferences as described above.

**Comment by Neberheim** [comment]
Excellent, thank you.

**Comment by dricard** [comment]
You're welcome!
